chore: Remove commented out code in 08-variables.yaml and 09-functions.yaml

diff --git a/.github/workflows/09-functions.yaml b/.github/workflows/09-functions.yaml
--- a/.github/workflows/09-functions.yaml
+++ b/.github/workflows/09-functions.yaml
@@ -14,8 +14,8 @@ jobs:
             - name: Testing success
               if: success()
               run: echo "Success!"
-            - name: failed step
-              run: exit 1
+            # - name: failed step
+            #   run: exit 1
             - name: Testing failure
               if: failure()
               run: echo "Failure!"
